### ISSUE TITLE
PHP Warning: Use of undefined constant TYPO3_cliMode 

### ISSUE THREAD

**Issue by pniederlag** [kaystrobach/TYPO3.dyncss#54]
`- assumed 'TYPO3_cliMode' (this will throw an Error in a future version of PHP) in /var/www/html/web/typo3conf/ext/dyncss/Classes/Service/DyncssService.php line 47`

should probably we changed to 

`!defined('TYPO3_cliMode')`

**Comment by pniederlag** [comment]
PR #53 is already in the pipe to address this matter, awesome

**Comment by CDRO** [comment]
I've checked this one and pulled the patch for my projects, it works well for now.

**Comment by bihor** [comment]
Well, but this problem is not only in TYPO3 8 relevant. With TYPO3 7.6.32 I get this warning with the current extension-version:
#1: PHP Warning: Use of undefined constant TYPO3_cliMode - assumed 'TYPO3_cliMode' (this will throw an Error in a future version of PHP) in /extern/agency/www/files/stark-fuer-ausbildung.de/typo3conf/ext/dyncss/Classes/Service/DyncssService.php line 62

**Comment by kaystrobach** [comment]
merged in master

**Comment by kaystrobach** [comment]
https://github.com/kaystrobach/TYPO3.dyncss/releases/tag/0.8.5

**Comment by bihor** [comment]
Yes, it is fixed for TYPO3 8, but still not for TYPO3 7...
I cant see any difference in version 0.8.5.
